services:
  backend:
    build:
      context: ./ex1
      dockerfile: Dockerfile
    ports:
      - "17000:17000"
    depends_on:
      - mongodb
  frontend:
    build:
      context: ./ex2
      dockerfile: Dockerfile
    ports:
      - "17001:17001"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - /home/jotaalvim/Documents/uni/engWeb/ENGWEB2024-Recurso/new_dataset.json:/tmp/dataset.json
    command: mongoimport --host mongodb -d livros -c livros --type json --file new_dataset.json --jsonArray
